Use correct multiline in travis script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -44,8 +44,27 @@ jobs:
         sudo pip install codespell
       script:
         # Run a non-erroring version to report spelling errors using standard filters
-        echo -e "\nRunning codespell with standard filters (returns 0)\n"
-
-        echo -e "\n\nRunning codespell with custom filters (returns errorcode)\n"
-
+        - echo -e "\nRunning codespell with standard filters (returns 0)\n"
+        - codespell
+          # skip these directories and file types
+          --skip="assets,bin,css,data,deprecated,fig,files,AUTHORS,CONTRIBUTORS.md,*.csv,.mailmap"
+          # keep reporting to what is necessary
+          --quiet-level=2
+          # allow for some false positives
+          --ignore-words-list="rouge,keyserver"
+          # do not return an error code
+          ||true
+        # Run an error reporting version (which may be customized for the repo):
+        # - Filter ipynb since any included images give a lot of false positives (other errors will be reported with the
+        #   non-erroring version above)
+        # - For this repo we also check the bin directory for spelling errors
+        # - Add comments on additional filters here (could also include regex with `--regex`)
+        - echo -e "\n\nRunning codespell with custom filters (returns errorcode)\n"
+        - codespell
+          # skip these directories and file types
+          --skip="assets,fig,*.svg,AUTHORS,.mailmap"
+          # keep reporting to what is necessary
+          --quiet-level=2
+          # allow for some false positives
+          --ignore-words-list="rouge,keyserver"
     - stage: check_and_build
